// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_Cimw6QSeQ1an5-Iltx0Jcx7luWUIiQc',
    appId: '1:699321428966:web:6c9798586a582c222d0427',
    messagingSenderId: '699321428966',
    projectId: 'fcmmessaging-a86fd',
    authDomain: 'fcmmessaging-a86fd.firebaseapp.com',
    databaseURL: 'https://fcmmessaging-a86fd.firebaseio.com',
    storageBucket: 'fcmmessaging-a86fd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeluHdCReRFmIoDm5q_b6IwD02JFk2c8k',
    appId: '1:699321428966:android:9dae9ccad57ff54d2d0427',
    messagingSenderId: '699321428966',
    projectId: 'fcmmessaging-a86fd',
    databaseURL: 'https://fcmmessaging-a86fd.firebaseio.com',
    storageBucket: 'fcmmessaging-a86fd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZ5ox4MckyS2D_n8KR2rcGzQvAdtwKslo',
    appId: '1:699321428966:ios:cd5829aa8d770fcd2d0427',
    messagingSenderId: '699321428966',
    projectId: 'fcmmessaging-a86fd',
    databaseURL: 'https://fcmmessaging-a86fd.firebaseio.com',
    storageBucket: 'fcmmessaging-a86fd.appspot.com',
    androidClientId: '699321428966-loi3bmj7otes22r7cmlmlqjdhgbl05s1.apps.googleusercontent.com',
    iosClientId: '699321428966-mpeen0jtelmc0om37tacdpijs8rak1tq.apps.googleusercontent.com',
    iosBundleId: 'com.example.formvalid',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZ5ox4MckyS2D_n8KR2rcGzQvAdtwKslo',
    appId: '1:699321428966:ios:cd5829aa8d770fcd2d0427',
    messagingSenderId: '699321428966',
    projectId: 'fcmmessaging-a86fd',
    databaseURL: 'https://fcmmessaging-a86fd.firebaseio.com',
    storageBucket: 'fcmmessaging-a86fd.appspot.com',
    androidClientId: '699321428966-loi3bmj7otes22r7cmlmlqjdhgbl05s1.apps.googleusercontent.com',
    iosClientId: '699321428966-mpeen0jtelmc0om37tacdpijs8rak1tq.apps.googleusercontent.com',
    iosBundleId: 'com.example.formvalid',
  );
}
